version: "2.2"
services:
  meso_gui:
    build: .
    volumes:
      - ./:/src/gui/
      - ../datajoint-dashboard:/src/datajoint-dashboard
    ports:
      - 9999:8000
    env_file: .env
    working_dir: /src/gui
    command: bash -c ". /root/.bashrc && pip install -e /src/datajoint-dashboard && python odor_meso_gui/index.py"
    networks:
      - meso
networks:
  meso:
